### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by RADICALAdrift** [onebeastchris/PickPack#15]
Hello,

I got your extension downloaded and setup but get an error executing the command /pickpack menu
09:16:07 [INFO] .RADICALAdrift executed command: /pickpack menu
09:16:07 [WARNING] Error in dispatching command
https://pastebin.com/raw/kkqcXDn3 <-- full error here

Many Thanks,
RADICALAdrift

**Comment by onebeastchris** [comment]
Hm, this one is odd..
Do you get any other errors from pickpack?
The only way this might happen would be if the locale wasn't properly copied from the jar, there should be a separate warning/error for that

**Comment by RADICALAdrift** [comment]
Only errors about the pack i am using but that might just be because i downloaded the wrong version, 
/pickpack reload and /pickpack default work fine just /pickpack menu throws that error

**Comment by onebeastchris** [comment]
Could you please send a full log & a copy of the pickpack config?
Something doesn't add up here

**Comment by RADICALAdrift** [comment]
Here's the full log and config files, 
It shouldn't matter i am running it on bungeecord right?.. If it does then there lays the problem

[full_log.txt](https://github.com/onebeastchris/PickPack/files/13412231/full_log.txt)

[config.txt](https://github.com/onebeastchris/PickPack/files/13412241/config.txt)

**Comment by onebeastchris** [comment]
Weird, it looks like the language manager might not be loaded.. ill test on Bungee later.
As for why you're getting errors spammed in both Geyser/Pickpack - you are trying to load a java edition resource pack. Pickpack only supports sending Bedrock edition packs to Bedrock edition players; so you'll need to find a Bedrock equivalent first (or convert the pack manually.)

However, pack and language manager loading are separated, so that error doesnt really add up - i'll set up a bungee environment to test the issue later today.

**Comment by RADICALAdrift** [comment]
Yeah i fixed the pack problem with the Bedrock equivalent so those errors are gone except this one that i have now

[Geyser-BungeeCord] The resource pack Faithful 32x - 1.20.mcpack has a file in it that meets or exceeds 80 characters in its path (textures/gui/newgui/buttons/checkbox/checkbox_unchecked_WhiteBorder_disabled.png, 80 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file.

But i could probably fix that easily by renaming or placing the file closer to the root of the pack

**Comment by RADICALAdrift** [comment]
Oh no rush, I appreciate you are going to test later today, for now i could just load said pack via geyser itself to play

**Comment by RADICALAdrift** [comment]
Sorry to be a bother, Have you managed to setup a test environment at all yet.. all good if you have im just curious is all as thats the last thing for my bedrock support setup

**Comment by onebeastchris** [comment]
Update PickPack to 1.2.1; issue should be fixed now. You may also want to delete the `lang` folder, it was accidentally created

**Comment by RADICALAdrift** [comment]
Working as intended now, Thank you

**Comment by onebeastchris** [comment]
np! Thanks for making an issue :)
